name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        # Install latest GCC.
        sudo apt install -y g++-12
        # Prepare a GCC toolchain dir for Clang. Clang 12 is incompatible with libstdc++ 12, even though it tries to use it.
        sudo mkdir -p gcc-toolchain-11/include/c++
        sudo ln -s /usr/include/c++/11 gcc-toolchain-11/include/c++/11
        sudo mkdir -p gcc-toolchain-11/lib/gcc/x86_64-unknown-linux-gnu
        sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/11 gcc-toolchain-11/lib/gcc/x86_64-unknown-linux-gnu/11
    - name: List compilers
      run: make -pq | grep ^COMPILER
    - name: Run tests
      run: make CXXFLAGS_PER_COMPILER='clang++-12=--gcc-toolchain=gcc-toolchain-11'
  Tests-MSVC:
    runs-on: windows-latest
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: make
        path-type: inherit
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        msvc_env_bat_files=( '/c/Program Files'*/'Microsoft Visual Studio'/*/*/'VC/Auxiliary/Build/vcvars64.bat' )
        echo >run.bat 'call "'"$(cygpath -w "${msvc_env_bat_files[-1]}")"'"'
        echo >>run.bat 'make COMPILER="cl clang-cl"'
        cat run.bat
        cmd /C run.bat
      shell: msys2 {0}
